services:

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    restart: unless-stopped

  nginx:
    image: nginx:${NGINX_VERSION}
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NODE_PORT=${NODE_PORT}
      - TZ=${TZ}
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./frontend:/vesp/frontend
      - ./www:/vesp/www
    ports:
      - ${NGINX_HOST}:${NGINX_PORT}:80
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mariadb

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_XDEBUG=${PHP_XDEBUG:-0}
        - TZ=${TZ}
    volumes:
      - ./.env:/vesp/.env
      - ./core:/vesp/core
      - ./www:/vesp/www
      - ./upload:/vesp/upload
      - ./tmp:/vesp/tmp
      - ./log:/vesp/log
      - ./frontend:/vesp/frontend
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mariadb
    environment:
      - TZ=${TZ}
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_IDE_CONFIG=serverName=VespDocker
    restart: unless-stopped
    command: sh -c 'composer install --no-dev && composer db:migrate && php-fpm'

  supervisor:
    build:
      context: ./docker/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_XDEBUG=${PHP_XDEBUG:-0}
        - TZ=${TZ}
    volumes:
      - ./.env:/vesp/.env
      - ./core:/vesp/core
      - ./www:/vesp/www
      - ./upload:/vesp/upload
      - ./tmp:/vesp/tmp
      - ./log:/vesp/log
      - ./frontend:/vesp/frontend
      - ./docker/php-fpm/supervisor/supervisord.conf:/etc/supervisord.conf
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mariadb
    environment:
      - TZ=${TZ}
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_IDE_CONFIG=serverName=VespDocker
    restart: unless-stopped
    user: "root"
    command: [ "supervisord" ]


  node:
    image: node:${NODE_VERSION}
    volumes:
      - ./.env:/vesp/.env
      - ./frontend:/vesp/frontend
    depends_on:
      - nginx
    environment:
      - TZ=${TZ}
    network_mode: 'service:nginx'
    restart: unless-stopped
    working_dir: /vesp/frontend
    command: sh -c 'rm -rf /tmp/* && yarn --prod && yarn build && node ./.output/server/index.mjs'

  redis:
    image: redis:${REDIS_VERSION}
    environment:
      - TZ=${TZ}
